# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volcanes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.IntegerField()),
                ('NOMBREVOLC', models.CharField(max_length=200)),
                ('ALTURASOBR', models.CharField(max_length=1024)),
                ('LATITUD', models.CharField(max_length=50)),
                ('LONGITUD', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=1024)),
                ('ACTIVIDAD', models.CharField(max_length=50)),
                ('IMAGEN', models.CharField(max_length=500)),
                ('DETALLE', models.CharField(max_length=500)),
                ('IMAGENESGALERIA', models.CharField(max_length=500)),
            ],
        ),
    ]
