# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolcanesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volcanes',
            name='id',
        ),
        migrations.AlterField(
            model_name='volcanes',
            name='OBJECTID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
